`default_nettype none

`ifndef __USER_DEFINES_H
`define __USER_DEFINES_H

// ============================================================================
// GPIO mode encodings (from caravel defs.h)
// ============================================================================
`define GPIO_MODE_INVALID                  13'hXXXX

// Management SoC Modes
`define GPIO_MODE_MGMT_STD_INPUT_NOPULL    13'h0403
`define GPIO_MODE_MGMT_STD_INPUT_PULLDOWN  13'h0c01
`define GPIO_MODE_MGMT_STD_INPUT_PULLUP    13'h0801
`define GPIO_MODE_MGMT_STD_OUTPUT          13'h1809
`define GPIO_MODE_MGMT_STD_BIDIRECTIONAL   13'h1801
`define GPIO_MODE_MGMT_STD_ANALOG          13'h000b

// User Project Modes
`define GPIO_MODE_USER_STD_INPUT_NOPULL    13'h0402
`define GPIO_MODE_USER_STD_INPUT_PULLDOWN  13'h0c00
`define GPIO_MODE_USER_STD_INPUT_PULLUP    13'h0800
`define GPIO_MODE_USER_STD_OUTPUT          13'h1808
`define GPIO_MODE_USER_STD_BIDIRECTIONAL   13'h1800
`define GPIO_MODE_USER_STD_OUT_MONITORED   13'h1802
`define GPIO_MODE_USER_STD_ANALOG          13'h000a

// ============================================================================
// GPIO configuration in NUMERICAL ORDER (0 → 37)
//
// analog_io[0]  = GPIO 7
// analog_io[n]  = GPIO (7 + n)
// ============================================================================

// GPIO 0–4 : SPI / debug (do not touch)
`define USER_CONFIG_GPIO_0_INIT  `GPIO_MODE_MGMT_STD_INPUT_NOPULL
`define USER_CONFIG_GPIO_1_INIT  `GPIO_MODE_MGMT_STD_INPUT_NOPULL
`define USER_CONFIG_GPIO_2_INIT  `GPIO_MODE_MGMT_STD_INPUT_NOPULL
`define USER_CONFIG_GPIO_3_INIT  `GPIO_MODE_MGMT_STD_INPUT_NOPULL
`define USER_CONFIG_GPIO_4_INIT  `GPIO_MODE_MGMT_STD_INPUT_NOPULL

// GPIO 5–6 : unused → analog (safe)
`define USER_CONFIG_GPIO_5_INIT  `GPIO_MODE_USER_STD_INPUT_PULLDOWN
`define USER_CONFIG_GPIO_6_INIT  `GPIO_MODE_USER_STD_INPUT_PULLDOWN
`define USER_CONFIG_GPIO_7_INIT  `GPIO_MODE_USER_STD_INPUT_PULLDOWN
`define USER_CONFIG_GPIO_8_INIT  `GPIO_MODE_USER_STD_INPUT_PULLDOWN
`define USER_CONFIG_GPIO_9_INIT  `GPIO_MODE_USER_STD_INPUT_PULLDOWN
`define USER_CONFIG_GPIO_10_INIT `GPIO_MODE_USER_STD_INPUT_PULLDOWN


// rx_data
`define USER_CONFIG_GPIO_11_INIT `GPIO_MODE_USER_STD_OUTPUT
`define USER_CONFIG_GPIO_12_INIT `GPIO_MODE_USER_STD_OUTPUT
`define USER_CONFIG_GPIO_13_INIT `GPIO_MODE_USER_STD_OUTPUT
`define USER_CONFIG_GPIO_14_INIT `GPIO_MODE_USER_STD_OUTPUT
`define USER_CONFIG_GPIO_15_INIT `GPIO_MODE_USER_STD_OUTPUT
`define USER_CONFIG_GPIO_16_INIT `GPIO_MODE_USER_STD_OUTPUT
`define USER_CONFIG_GPIO_17_INIT `GPIO_MODE_USER_STD_OUTPUT
`define USER_CONFIG_GPIO_18_INIT `GPIO_MODE_USER_STD_OUTPUT

// rx_ack_wire
`define USER_CONFIG_GPIO_19_INIT `GPIO_MODE_USER_STD_OUTPUT

// active_mode_wire
`define USER_CONFIG_GPIO_20_INIT `GPIO_MODE_USER_STD_OUTPUT
`define USER_CONFIG_GPIO_21_INIT `GPIO_MODE_USER_STD_OUTPUT


// rx_valid_wire
`define USER_CONFIG_GPIO_22_INIT `GPIO_MODE_USER_STD_OUTPUT

// scan_out_cc_wire
`define USER_CONFIG_GPIO_23_INIT `GPIO_MODE_USER_STD_OUTPUT

// ScanInDR
`define USER_CONFIG_GPIO_24_INIT `GPIO_MODE_USER_STD_INPUT_PULLDOWN

// TM
`define USER_CONFIG_GPIO_25_INIT `GPIO_MODE_USER_STD_INPUT_PULLDOWN

// Analog
`define USER_CONFIG_GPIO_26_INIT `GPIO_MODE_USER_STD_ANALOG
`define USER_CONFIG_GPIO_27_INIT `GPIO_MODE_USER_STD_ANALOG
`define USER_CONFIG_GPIO_28_INIT `GPIO_MODE_USER_STD_ANALOG
`define USER_CONFIG_GPIO_29_INIT `GPIO_MODE_USER_STD_ANALOG
`define USER_CONFIG_GPIO_30_INIT `GPIO_MODE_USER_STD_ANALOG
`define USER_CONFIG_GPIO_31_INIT `GPIO_MODE_USER_STD_ANALOG
`define USER_CONFIG_GPIO_32_INIT `GPIO_MODE_USER_STD_ANALOG
`define USER_CONFIG_GPIO_33_INIT `GPIO_MODE_USER_STD_ANALOG
`define USER_CONFIG_GPIO_34_INIT `GPIO_MODE_USER_STD_ANALOG
`define USER_CONFIG_GPIO_35_INIT `GPIO_MODE_USER_STD_ANALOG

// IP other digital signals
`define USER_CONFIG_GPIO_36_INIT `GPIO_MODE_USER_STD_INPUT_PULLDOWN
`define USER_CONFIG_GPIO_37_INIT `GPIO_MODE_USER_STD_INPUT_PULLDOWN

`endif // __USER_DEFINES_H

